### ISSUE TITLE
How to train the CNN filters

### ISSUE THREAD

**Issue by shqing** [pquochuy/MultitaskSleepNet#1]
Hello, if i want to train the filterbanks of CNN, how should I do? By executing the script  tensorflow_net/dnn-filterbank/train_dnn_filterbank_gpu0 ? How this script is to train the filters of DNN.

**Comment by pquochuy** [comment]
Hi shqing,

To train the DNN filterbanks, you have first download the datasets and prepare the data as I described in Step 1 and 2. Afterwards, you can execute the following script: 

- `tensorflow_net/dnn-filterbank/run_eeg.sh` for EEG filterbanks
- `tensorflow_net/dnn-filterbank/run_eog.sh` for EOG filterbanks
- `tensorflow_net/dnn-filterbank/run_eog.sh` for EMG filterbanks

If you view the script file, you can see they basically call `train_dnn_filterbank_gpu0.py` and `test_dnn_filterbank_gpu0.py` 

Hope this would help and please let me know if something goes wrong.

Huy
