### ISSUE TITLE
EDF annotations 

### ISSUE THREAD

**Issue by emadeldeen24** [pquochuy/MultitaskSleepNet#3]
Can you please provide the EDF annotations for the rest of the EDF files?
[here ](https://github.com/pquochuy/MultitaskSleepNet/tree/master/SleepEDF/data_processing/sleepedfx_database), you only provide them for 20 SC* subjects. Can you provide them for the 153 subjects?
because the download link is not working.

**Comment by pquochuy** [comment]
Hi, 

What do you mean by EDF annotations? Are they the hypnograms? If so, you should be able to download them from here: https://physionet.org/content/sleep-edfx/1.0.0/

Anyway, just to clarify that we used the dataset version consisting of 20 SC* subjects in this paper, not the latest with 153 nights.

**Comment by emadeldeen24** [comment]
Thank you for your quick reply.
I mean these info files https://github.com/pquochuy/MultitaskSleepNet/tree/master/SleepEDF/data_processing/sleepedfx_database/SC4001E0/info

Do you have them for the rest of the SC subjects?

**Comment by pquochuy** [comment]
Ah, I see. If you let me know your email address, I can send them to you.

**Comment by emadeldeen24** [comment]
emadeldin_ahmed@hotmail.com
